# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-21 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=255, verbose_name='部门')),
            ],
            options={
                'verbose_name': '部门信息表',
                'verbose_name_plural': '部门信息表',
                'db_table': 'tb_dept',
            },
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_name', models.CharField(max_length=255, verbose_name='姓名')),
                ('em_sex', models.CharField(max_length=6, verbose_name='性别')),
                ('em_age', models.IntegerField(default=18, verbose_name='年龄')),
                ('em_telephone', models.CharField(max_length=15, verbose_name='电话号码')),
                ('entry_time', models.DateField(verbose_name='入职时间')),
                ('dept_name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='tb_employee.DeptInfo', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '员工信息表',
                'verbose_name_plural': '员工信息表',
                'db_table': 'tb_employee',
            },
        ),
    ]
