# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-23 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20, verbose_name='主机名')),
                ('sbrand', models.CharField(default='戴尔', max_length=200, verbose_name='品牌')),
                ('sip', models.CharField(default='127.0.0.1', max_length=40, verbose_name='内网IP')),
                ('stdisk', models.IntegerField(default=5, verbose_name='磁盘总大小')),
                ('sfdisk', models.IntegerField(default=5, verbose_name='磁盘剩余量')),
                ('stmemory', models.IntegerField(default=5, verbose_name='总内存')),
                ('sfmemory', models.IntegerField(default=5, verbose_name='剩余内存')),
                ('screate_date', models.DateField(verbose_name='创建日期')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'db_table': 'tb_servers',
            },
        ),
    ]
